insert into STOCK_PRICE(STOCK_ID,STOCK_COMPANY_NAME,STOCK_COPMANY_PRICE)values(101,'HCL',77.5)
insert into STOCK_PRICE(STOCK_ID,STOCK_COMPANY_NAME,STOCK_COPMANY_PRICE)values(102,'BHEL',77.5)
insert into STOCK_PRICE(STOCK_ID,STOCK_COMPANY_NAME,STOCK_COPMANY_PRICE)values(103,'TCS',77.5)
insert into STOCK_PRICE(STOCK_ID,STOCK_COMPANY_NAME,STOCK_COPMANY_PRICE)values(104,'HCL',77.5)